### PR TITLE
check_dockerhub_repo_build_status: --repo: allow dots

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before/after

```
(venv) ➜  HariSekhon-Nagios-Plugins git:(master) ./check_dockerhub_repo_build_status.py --repo grandmaster/votesmart.nerezidenti.org
/Users/aklimov/Git/HariSekhon-Nagios-Plugins/venv/lib/python2.7/site-packages/requests_kerberos/kerberos_.py:10: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import x509
invalid repo 'grandmaster/votesmart.nerezidenti.org' defined - must be one of the following chars: A-Za-z0-9/_-

Usage: check_dockerhub_repo_build_status.py [options]

Options:
  -r REPO, --repo=REPO  DockerHub repository to check, in form of '<user>/<repo>' eg. harisekhon/pytools
  -T TAG, --tag=TAG     Check status of only this tag eg. latest or 2.7
  -p num, --pages=num   Max number of API pages to iterate on to find the latest build (default: 1). If increasing
                        this you will probably also need to increase --timeout
  -t secs, --timeout=secs
                        Timeout in secs ($TIMEOUT, default: 10)
  -v, --verbose         Verbose level ($VERBOSE=<int>, or use multiple -v, -vv, -vvv)
  -V, --version         Show version and exit
  -h, --help            Show full help and exit
(venv) ➜  HariSekhon-Nagios-Plugins git:(master) git co -
Zu Branch 'bugfix/repo-dots' gewechselt
Ihr Branch ist auf demselben Stand wie 'fork/bugfix/repo-dots'.
(venv) ➜  HariSekhon-Nagios-Plugins git:(bugfix/repo-dots) ./check_dockerhub_repo_build_status.py --repo grandmaster/votesmart.nerezidenti.org
/Users/aklimov/Git/HariSekhon-Nagios-Plugins/venv/lib/python2.7/site-packages/requests_kerberos/kerberos_.py:10: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import x509
CRITICAL: 404 NOT FOUND
(venv) ➜  HariSekhon-Nagios-Plugins git:(bugfix/repo-dots)
```

**Comment by HariSekhon** [comment]
Thanks for the patch!

**Comment by Al2Klimov** [comment]
You're welcome! When there will be a new Docker image? Oh, and do you know any way to workaround docker/hub-feedback#2065 in this plugin?

**Comment by HariSekhon** [comment]
One of those says
```
"is_automated": false
```
so I suspect it'll never have build history.

The other one appears to be configured automated, perhaps it hasn't built yet?

**Comment by Al2Klimov** [comment]
The web interface clearly shows a build history, doesn’t it?

**Comment by HariSekhon** [comment]
Yes you're right, I've just looked here:

https://hub.docker.com/r/grandmaster/build-check_linux_sensors-amd64/builds

I've encountered several bugs with DockerHub API around automated builds and statuses (eg. I've had to remove badges because of it), this is probably just another bug. DockerHub has been doing downhill for quite a while, and has recently imposed quite low pull limits.

The new build is available on DockerHub now.

If you ever want to rebuild it yourself from Dockerfile source and push to your own repo, you can find the Dockerfiles for all major distros here:

https://github.com/HariSekhon/Dockerfiles

**Pull request merged**
